name: wai_eng
description: Simple flashcard with simple operation.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.10.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sprung: ^3.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sembast
      version: '>=0.3.0'
  settings_ui: ^2.0.2
  csv: ^5.0.2
  share_plus: ^10.1.3
  path_provider: ^2.0.15
  adaptive_dialog: ^2.4.0-0
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.1
flutter:
  uses-material-design: true
  assets:
      - assets/icon.png
      - lib/modules/swipable_stack/LICENSE
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"

flutter_native_splash:
  image: "lib/assets/icon.png"
  color: "000000"
