name: wai_eng
description: A flashcard App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sprung: ^3.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.1
flutter:
  uses-material-design: true
  assets:
      - lib/assets/icon.png
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"

flutter_native_splash:
  image: "lib/assets/icon.png"
  color: "000000"
