name: wai_eng
description: Simple flashcard with simple operation.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  sprung: ^3.0.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sembast
      version: '>=0.3.0'
  settings_ui: ^2.0.2
  csv: ^5.0.2
  share_plus: ^10.1.3
  path_provider: ^2.0.15
  adaptive_dialog: ^2.4.0-0
  wakelock_plus: ^1.2.10
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
flutter:
  uses-material-design: true
  assets:
      - assets/logo_rounded.png
      - lib/modules/swipable_stack/LICENSE
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/logo.png"
  image_path: "assets/logo_rounded.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo_rounded.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo_rounded.png"
  macos:
    generate: true
    image_path: "assets/logo_rounded.png"

flutter_native_splash:
  image: "assets/logo.png"
  color: "000000"
